spring:
    application:
        name: enviroCar - BIGIOT WFS Adapter

ec4bit:
    contact: envirocar@52north.org
    
bigiot:
    marketplace:
        url:  https://market.big-iot.org
    provider:
        address: localhost
        port: 7776
        
wfs:
    url: http://geodienste.hamburg.de/HH_WFS_Verkehr_opendata
    service: WFS
    version: 1.1.0
    request: GetFeature
    typeName: app:parkandride_os
    outputFormat: text/xml; subtype=gml/2.1.2
    
offering:
    local_id: highway-traffic-offering
    withInformation:
        name:   (Testing) / HIGHWAY_TRAFFIC-OFFERING
        schema: SCHEMA_HIGHWAY_TRAFFIC
    route: highways
    inCity: Hamburg
    expireDate: 2018-02-28T01:23:45
    accessStreamTimeout: 2018-02-28T01:23:45
    licenseType: NON_COMMERCIAL_DATA_LICENSE
    price:
        pricingModel: FREE
        price: 0.00
        currency: Euros
    geometry:
        name: position
        schema: http://schema.org/point
    featureIdentifier:
        name: featureID
        schema: http://schema.org/identifier
    mapNullValues: false
    outputData:
        -   name : bahnstation
            schema: SCHEMA_AMOUNT
        -   name : art
            schema: SCHEMA_AMOUNT
        -   name : einfahrt
            schema: SCHEMA_AMOUNT
        -   name : allgemeinest_gesamt
            schema: SCHEMA_AMOUNT
        -   name : entgeltpflichtig
            schema: SCHEMA_AMOUNT
        -   name : preise
            schema: SCHEMA_AMOUNT
        -   name : stellplaetze_gesamt
            schema: SCHEMA_AMOUNT
        -   name : pur
            schema: SCHEMA_AMOUNT
        -   name : datenherkunft
            schema: SCHEMA_AMOUNT