spring:
    application:
        name: enviroCar - BIGIOT WFS Adapter

ec4bit:
    contact: envirocar@52north.org
    
bigiot:
    marketplace:
        url:  https://market.big-iot.org
    provider:
        address: localhost
        port: 7772
        
wfs:
    url: https://data.wien.gv.at/daten/geo
    service: WFS
    version: 1.1.0
    request: GetFeature
    typeName: ogdwien:OEFFHALTESTOGD
    outputFormat: text/xml; subtype=gml/2.1.2
    srsName: EPSG:4326
    
offering:
    local_id: vienna_busstops_offering
    name:   Vienna_Busstops
    category: urn:proposed:Busstops
    timePeriod:
        startDate: 2007-01-01T00:00:00
        endDate: 2016-12-30T22:55:55
    inRegion:
        x1: 48.118937
        y1: 16.175432
        x2: 48.317039
        y2: 16.594972
    inCity: Vienna
    inCountry: Austria
    route: busstops
    expireDate: 2018-02-28T01:23:45
#    accessStreamTimeout: 2018-02-28T01:23:45
    licenseType: NON_COMMERCIAL_DATA_LICENSE
    price:
        pricingModel: FREE
        price: 0.00
        currency: Euros
    geometry:
        name: SHAPE
        schema: http://schema.org/point
    featureIdentifier:
        name: featureID
        schema: proposed:id
    mapNullValues: false
    outputData:
        -   name : OBJECTID
            schema: proposed:id
        -   name : HTXT
            schema: proposed:location_name
        -   name : HTXTK
            schema: proposed:location_name
        -   name : HLINIEN
            schema: proposed:bus_line_number
        -   name : DIVA_ID
            schema: proposed:id