spring:
    application:
        name: enviroCar - BIGIOT WFS Adapter

ec4bit:
    contact: envirocar@52north.org
    
bigiot:
    marketplace:
        url:  https://market.big-iot.org
    provider:
        address: localhost
        port: 7778
        
offering:
    # required parameters:
    url: http://processing.envirocar.org:9090/geoserver/cite/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=cite:roadsegments&outputFormat=text%2Fxml%3B%20subtype%3Dgml%2F2.1.2
    local_id: roadsegments-offering
    withInformation:
        name:   (Testing) / WFS-OFFERING-ROADSEGMENTS
        schema: SCHEMA_ROAD_SEGMENTS
    # optional parameters:
    route: roadsegments
    inCity: Barcelona
    expireDate: 2018-01-30T01:23:45
    licenseType: OPEN_DATA_LICENSE
    price:
        # pricingModel options: { FREE, PER_ACCESS, PER_BYTE, PER_MESSAGE, PER_MONTH }, Default: FREE
        pricingModel: FREE
        price: 0.00
        # currency options: { Euros, USDollers }, Default: Euros
        currency: Euros
    geometry:
        name: geom
        schema: http://schema.org/line
    outputData:
        -   name: OSMID
            schema: http://schema.org/identifier
        -   name: sumGPSAccuracy
            schema: SCHEMA_SUM_GPS_ACCURACY
        -   name: avgGPSAccuracy
            schema: SCHEMA_AVG_GPS_ACCURACY
        -   name: numGPSAccuracy
            schema: SCHEMA_AMOUNT
        -   name: sumGPSAltitude
            schema: http://schema.org/elevation
        -   name: avgGPSAltitude
            schema: http://schema.org/elevation
        -   name: numGPSAltitude
            schema: SCHEMA_AMOUNT
        -   name: sumGPSBearing
            schema: SCHEMA_GPS_BEARING 
        -   name: avgGPSBearing
            schema: SCHEMA_GPS_BEARING 
        -   name: numGPSBearing
            schema: SCHEMA_AMOUNT
        -   name: sumGPSHDOP
            schema: SCHEMA_SUM_SUM_GPS_HDOP
        -   name: avgGPSHDOP
            schema: SCHEMA_AVG_GPS_HDOP
        -   name: numGPSHDOP
            schema: SCHEMA_AMOUNT
        -   name: sumGPSPDOP
            schema: SCHEMA_SUM_GPS_PDOP
        -   name: avgGPSPDOP
            schema: SCHEMA_AVG_GPS_PDOP
        -   name: numGPSPDOP
            schema: SCHEMA_AMOUNT
        -   name: sumGPSSpeed
            schema: http://auto.schema.org/speed
        -   name: avgGPSSpeed
            schema: http://auto.schema.org/speed
        -   name: numGPSSpeed
            schema: SCHEMA_AMOUNT
        -   name: sumGPSVDOP
            schema: SCHEMA_SUM_GPS_VDOP
        -   name: avgGPSVDOP
            schema: SCHEMA_AVG_GPS_VDOP
        -   name: numGPSVDOP
            schema: SCHEMA_AMOUNT
        -   name : sumIntakePressure
            schema: SCHEMA_SUM_INTAKE_PRESSURE
        -   name : avgIntakePressure
            schema: SCHEMA_AVG_INTAKE_PRESSURE
        -   name : numIntakePressure
            schema: SCHEMA_AMOUNT
        -   name : sumIntakeTemperature
            schema: SCHEMA_SUM_INTAKE_TEMPERATURE
        -   name : avgIntakeTemperature
            schema: SCHEMA_AVG_INTAKE_TEMPERATURE
        -   name : numIntakeTemperature
            schema: SCHEMA_AMOUNT
        -   name : sumMAF
            schema: SCHEMA_SUM_MAF
        -   name : avgMAF
            schema: SCHEMA_AVG_MAF
        -   name : numMAF
            schema: SCHEMA_AMOUNT
        -   name : sumO2LambdaVoltage
            schema: SCHEMA_SUM_SUM_O2_LAMBDA_VOLTAGE
        -   name : avgO2LambdaVoltage
            schema: SCHEMA_AVG_SUM_O2_LAMBDA_VOLTAGE
        -   name : numO2LambdaVoltage
            schema: SCHEMA_AMOUNT
        -   name : sumO2LambdaVoltageER
            schema: SCHEMA_SUM_SUM_O2_LAMBDA_VOLTAGE_ER
        -   name : avgO2LambdaVoltageER
            schema: SCHEMA_AVG_SUM_O2_LAMBDA_VOLTAGE_ER
        -   name : numO2LambdaVoltageER
            schema: SCHEMA_AMOUNT
        -   name : sumRpm
            schema: SCHEMA_SUM_RPM
        -   name : avgRpm
            schema: SCHEMA_AVG_RPM
        -   name : numRpm
            schema: SCHEMA_AMOUNT
        -   name : sumSpeed
            schema: http://auto.schema.org/speed
        -   name : avgSpeed
            schema: http://auto.schema.org/speed
        -   name : numSpeed
            schema: SCHEMA_AMOUNT
        -   name : sumThrottlePosition
            schema: SCHEMA_SUM_THROTTLE_POSITION
        -   name : avgThrottlePosition
            schema: SCHEMA_AVG_THROTTLE_POSITION
        -   name : numThrottlePosition
            schema: SCHEMA_AMOUNT
        -   name : sumCO2
            schema: http://auto.schema.org/emissionsCO2
        -   name : avgCO2
            schema: http://auto.schema.org/emissionsCO2
        -   name : numCO2
            schema: SCHEMA_AMOUNT
        -   name : sumEngineLoad
            schema: SCHEMA_SUM_ENGINE_LOAD
        -   name : avgEngineLoad
            schema: SCHEMA_AVG_ENGINE_LOAD
        -   name : numEngineLoad
            schema: SCHEMA_AMOUNT
        -   name : sumConsumption
            schema: http://schema.org/fuelConsumption
        -   name : avgConsumption
            schema: http://schema.org/fuelConsumption
        -   name : numConsumption
            schema: SCHEMA_AMOUNT

#    url: http://processing.envirocar.org:9090/geoserver/sf/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=sf:roads&outputFormat=gml3
#    local_id: test-wfsOfferings-spearfish-roads
#    offeringName: (Testing) / WFS-OFFERING-SPEARFISHROADS
#    offeringSchema: SCHEMA_SPEARFISH_ROADS
#    offeringRoute: roads
#    geometry:
#        name: geom
#        schema: http://schema.org/roads
#    outputData:
#        -   name: cat
#            schema: SCHEMA_MEOW
#        -   name: label
#            schema: SCHEMA_LABEL